#!/usr/bin/env bash
# Opens a draft PR for a completed task in a worktree.
# Usage: open-task-pr.sh <worktree-path> <task-description> <commit-message>

set -euo pipefail

if [ $# -lt 3 ]; then
  echo "Usage: $0 <worktree-path> <task-description> <commit-message>" >&2
  exit 1
fi

WORKTREE_PATH="$1"
TASK_DESCRIPTION="$2"
COMMIT_MSG="$3"

cd "$WORKTREE_PATH"

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "development" ]; then
  echo "ERROR: refusing to open PR from $BRANCH" >&2
  exit 1
fi

git add -A
if git diff --staged --quiet; then
  echo "No changes to commit"
  exit 1
fi

git commit -m "$COMMIT_MSG"
git push -u origin "$BRANCH"

FILES=$(git diff --name-only origin/development...HEAD)
TITLE=$(echo "$COMMIT_MSG" | head -1)

BODY=$(cat <<EOF
## Task
$TASK_DESCRIPTION

## Files changed
\`\`\`
$FILES
\`\`\`

## Local gate (Plan A)
- pytest: passed
- ruff check: passed
- ruff format: passed

Generated by VisionForge agent team.
EOF
)

PR_URL=$(gh pr create --base development --draft --title "$TITLE" --body "$BODY")
echo "$PR_URL"
