"""Scaffolder behind ``visionforge new-task`` (ADR-058, brick 5).

Generates a self-contained, functional task file under ``user_tasks/``: the
template registers a real task that trains on synthetic data out of the box,
with loud TODO markers where the researcher plugs in their dataset, model,
loss and metrics. One file — the discovery loader imports each task file as a
standalone module (no package semantics), so splitting the template across
sibling modules would break relative imports.
"""

from __future__ import annotations

from pathlib import Path

from visionforge.tasks.registry import (
    _KEY_RE,
    BUILTIN_TASK_KEYS,
    DEFAULT_USER_TASKS_DIR,
)

_TEMPLATE = '''"""Custom VisionForge task: __LABEL__.

Generated by ``visionforge new-task __KEY__``. This file already works: it
registers the task, and the demo model below trains on synthetic data — open
the GUI and the "__LABEL__" tab is live. Replace each TODO with your real
dataset, model, loss and metrics.

[PT] Este arquivo já funciona: registra a tarefa e treina um modelo de
demonstração em dados sintéticos. Substitua cada TODO pelo seu dataset,
modelo, loss e métricas reais. Guia completo: user_tasks/README.md.

Endpoints you get for free once this file exists (no server restart needed):

    GET  /api/custom/__KEY__/schema        form schema (from Config below)
    POST /api/custom/__KEY__/run           one training run
    POST /api/custom/__KEY__/sweep         hyperparameter sweep (ADR-045)
    POST /api/custom/__KEY__/replicates    multi-seed replicates (ADR-056)

VisionForge's generic engine drives seeding, device placement, AMP, early
stopping, best-checkpoint selection, the SSE live monitor, TensorBoard and
run.json provenance — you only fill the four hooks (ADR-058). If your
training is not epoch-shaped (GANs, EM loops), override ``run(cfg, ctx)``
instead and own the loop; see TaskSpec.run.
"""

from __future__ import annotations

import torch
from pydantic import Field
from torch import nn
from torch.utils.data import DataLoader, Dataset

from visionforge.tasks import BaseTaskConfig, TaskSpec, register_task


class __CLASS__Config(BaseTaskConfig):
    """The GUI form for this task — rendered from this class's JSON schema.

    ``BaseTaskConfig`` already provides every shared knob:

    - ``name``               experiment name
    - ``data``               base_dir, image_size, num_workers, pin_memory,
                             transforms, preprocessing
    - ``training``           epochs, batch_size, learning_rate, optimizer,
                             weight_decay, seed, early_stopping_patience,
                             deterministic, mixed_precision, scheduler
    - ``output.models_dir``  where run directories land
    - ``device.kind``        auto | cuda | cpu

    Add ONLY task-specific fields. ``description=`` becomes the form's help
    text; constraints (``ge``/``gt``/``le``) reject bad values before any GPU
    time is spent.
    """

    # TODO: replace these demo fields with your task's real knobs.
    n_samples: int = Field(
        default=256, ge=8, description="Size of the synthetic demo dataset"
    )
    hidden_units: int = Field(default=32, ge=1, description="Demo model width")


# NOTE (Windows/ADR-030): a Dataset class defined in THIS file cannot be sent
# to DataLoader workers — spawn re-imports the dataset's module by name, and
# task files are loaded from a path, not an importable package. Keep
# num_workers=0 here, or define your Dataset in an installed package and use
# cfg.data.num_workers.
class SyntheticDataset(Dataset):
    """TODO: replace with your Dataset reading real files from cfg.data.base_dir."""

    def __init__(self, n: int, seed: int) -> None:
        gen = torch.Generator().manual_seed(seed)
        self.x = torch.randn(n, 8, generator=gen)
        # A fixed linear rule as target, so the demo loss actually drops.
        self.y = self.x @ torch.linspace(-1.0, 1.0, 8).unsqueeze(1)

    def __len__(self) -> int:
        return len(self.x)

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, torch.Tensor]:
        return self.x[idx], self.y[idx]


@register_task(
    key="__KEY__",
    label="__LABEL__",
    accent="#2dd4bf",  # tab color, #rrggbb — pick your own
    description="TODO: one line shown in the GUI task list",
    # Every metric compute_metrics returns, mapped to its direction —
    # "lower" (errors) or "higher" (scores). Drives ranking and plots.
    metrics={"mae": "lower"},
    primary_metric="mae",  # selects the best checkpoint + report headline
)
class __CLASS__Task(TaskSpec[__CLASS__Config]):
    """Level 1 custom task: four hooks, the engine owns the training loop."""

    Config = __CLASS__Config

    def build_model(self, cfg: __CLASS__Config) -> nn.Module:
        """Return a freshly-initialized model — any nn.Module works."""
        # TODO: your architecture here.
        return nn.Sequential(
            nn.Linear(8, cfg.hidden_units),
            nn.ReLU(),
            nn.Linear(cfg.hidden_units, 1),
        )

    def build_loaders(self, cfg: __CLASS__Config):
        """Return ``(train_loader, val_loader, test_loader_or_None)``."""
        # TODO: build real loaders from cfg.data.base_dir.
        train = SyntheticDataset(cfg.n_samples, seed=cfg.training.seed)
        val = SyntheticDataset(max(cfg.n_samples // 4, 8), seed=cfg.training.seed + 1)

        def _loader(ds: SyntheticDataset, shuffle: bool) -> DataLoader:
            # num_workers=0: see the SyntheticDataset note above (ADR-030).
            return DataLoader(
                ds, batch_size=cfg.training.batch_size, shuffle=shuffle, num_workers=0
            )

        return (
            _loader(train, shuffle=True),
            _loader(val, shuffle=False),
            None,  # a test loader here is also reported, as test_<metric>
        )

    def compute_loss(
        self, model: nn.Module, batch: tuple, cfg: __CLASS__Config
    ) -> torch.Tensor:
        """One batch -> scalar loss. Move the batch to the model's device."""
        device = next(model.parameters()).device
        inputs, targets = (t.to(device) for t in batch)
        # TODO: your loss here.
        return nn.functional.mse_loss(model(inputs), targets)

    def compute_metrics(
        self, model: nn.Module, loader: DataLoader, cfg: __CLASS__Config
    ) -> dict[str, float]:
        """Evaluate over ``loader`` -> {name: value} matching @register_task."""
        device = next(model.parameters()).device
        errors: list[float] = []
        with torch.no_grad():
            for inputs, targets in loader:
                pred = model(inputs.to(device))
                errors.append((pred - targets.to(device)).abs().mean().item())
        # TODO: your metrics here (keys must match the declaration above).
        return {"mae": sum(errors) / max(len(errors), 1)}
'''


def _class_name(key: str) -> str:
    return "".join(part.capitalize() for part in key.split("_"))


def _label(key: str) -> str:
    return key.replace("_", " ").capitalize()


def scaffold_task(
    key: str,
    *,
    directory: Path | str | None = None,
    package: bool = False,
    force: bool = False,
) -> Path:
    """Write the commented task template and return the created file's path.

    ``package=True`` creates ``<dir>/<key>/task.py`` (room for assets next to
    the code) instead of the flat ``<dir>/<key>.py``; discovery accepts both.

    Raises:
        ValueError: for an invalid key or a collision with a built-in task.
        FileExistsError: when the target exists and ``force`` is False.
    """
    if not _KEY_RE.match(key):
        raise ValueError(
            f"Task key '{key}' must be lowercase [a-z0-9_] and start with a letter."
        )
    if key in BUILTIN_TASK_KEYS:
        raise ValueError(f"Task key '{key}' collides with a built-in VisionForge task.")

    base = Path(directory) if directory is not None else DEFAULT_USER_TASKS_DIR
    target = base / key / "task.py" if package else base / f"{key}.py"
    if target.exists() and not force:
        raise FileExistsError(
            f"{target} already exists — pass --force to overwrite it."
        )

    content = (
        _TEMPLATE.replace("__KEY__", key)
        .replace("__CLASS__", _class_name(key))
        .replace("__LABEL__", _label(key))
    )
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    return target


__all__ = ["scaffold_task"]
